"""Migração Inicial

Revision ID: 6a33deadb597
Revises: 
Create Date: 2024-12-11 11:59:47.764700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a33deadb597'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_Doadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_Doacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('data', sa.DATE(), nullable=True),
    sa.Column('id_Doadores', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_Doadores'], ['tb_Doadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_Doacoes')
    op.drop_table('tb_Doadores')
    # ### end Alembic commands ###
